services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-img
    container_name: react-con
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8888:3000"
    command: npm start
    restart: unless-stopped